### PR TITLE
doc: Fix TOC numbers again

### PR DESCRIPTION
**Pull request by lencioni**
These numbers were messed up by ce34474322. I'm starting to think we
might need a linter for this.

### CODE REVIEW

**Comment by wincent** [comment]
Geez, WTF is wrong with me. I just mash <C-a> and <C-x> and evidently don't
even look at the screen.

Thanks for the fix. No need for a linter though; I'm working on a
documentation generator on the side that will build these for me.

**Comment by lencioni** [comment]
LOL, I was just joking about the linter ;) but the documentation generator sounds pretty cool. I'm a bit surprised that there isn't one already. But you're going to need it if you ever hope to catch up to Tim Pope!

**Comment by wincent** [comment]
There actually is already one that I know of (https://github.com/google/vimdoc), but it doesn't meet my use case which is wanting to generate Vim docs and Markdown from the same source files. Also, it's fun to build this kind of thing.

**Comment by lencioni** [comment]
Yeah, the markdown would be really nice. I wonder if you could write it mostly as markdown, and add some extensions that do the special Vim stuff you want?

**Comment by wincent** [comment]
That's exactly the idea. I wasn't going to push it until it's done, but if
you're interested I can share the very early WIP with you. At the moment
it's just a lexer and the beginnings of a parser.

**Comment by lencioni** [comment]
> If you're interested I can share the very early WIP with you

Nah, I probably won't have time to look at it.

> At the moment it's just a lexer and the beginnings of a parser.

Do either of the CommonMark reference implementations allow you to add extensions? It seems like a lot of work to do all of that yourself...

**Comment by wincent** [comment]
It's easier just to parse the (very small) subset of Markdown that can be
translated to Vim's "help" format, especially because there is no avoiding
having to parse the plugin source code to extract the doc comments.

**Comment by wincent** [comment]
Thanks for the PR, @lencioni.

**Comment by lencioni** [comment]
Here's a random and wacky thought: write your documentation with React and render it to markdown/Vim help file format.

**Comment by wincent** [comment]
That, combined with the use of immutable data structures, will dramatically
reduce the number of race conditions and hard to reproduce bugs in my help
files, right?

**Pull request closed without merging**
